import { useEffect, useState } from 'react'
import { Check } from 'lucide-react'
import { loadStoreSettings, saveStoreSettings, type StoreSettingsInput } from '../services/queueService'

type Props = { storeId?: string; accent: string; setAccent: (value: string) => void; onNotice: (message: string) => void }
const defaults: StoreSettingsInput = { name: 'Zé Barreiro', accentColor: '#FFC107', estimatedServiceTime: 10, callPhrase: '{name}, favor retirar o pedido.', callRepeat: 3, attendanceTimeout: 5, allowVoluntaryExit: true, allowNewEntries: true, tvPositions: 7, volume: 80 }

export default function SettingsSupabase({ storeId, accent, setAccent, onNotice }: Props) {
  const [form, setForm] = useState<StoreSettingsInput>({ ...defaults, accentColor: accent })
  const [loading, setLoading] = useState(Boolean(storeId))
  const [saving, setSaving] = useState(false)
  useEffect(() => { if (!storeId) return; void loadStoreSettings(storeId).then(({ store, settings }) => setForm({ name: store.name, accentColor: store.accent_color, estimatedServiceTime: store.estimated_service_time, callPhrase: store.call_phrase, callRepeat: store.call_repeat, attendanceTimeout: store.attendance_timeout, allowVoluntaryExit: store.allow_voluntary_exit, allowNewEntries: store.allow_new_entries, tvPositions: store.tv_positions, volume: settings?.volume ?? 80 })).catch(error => onNotice(error.message || 'Não foi possível carregar as configurações.')).finally(() => setLoading(false)) }, [storeId])
  const update = <K extends keyof StoreSettingsInput>(key: K, value: StoreSettingsInput[K]) => { setForm(current => ({ ...current, [key]: value })); if (key === 'accentColor') setAccent(String(value)) }
  const save = async () => { if (!storeId) { onNotice('A loja do Supabase não está configurada.'); return } setSaving(true); try { await saveStoreSettings(storeId, form); setAccent(form.accentColor); onNotice('Configurações salvas no Supabase.') } catch (error) { onNotice(error instanceof Error ? error.message : 'Não foi possível salvar as configurações.') } finally { setSaving(false) } }
  const number = (key: 'estimatedServiceTime' | 'callRepeat' | 'attendanceTimeout' | 'tvPositions' | 'volume') => (event: React.ChangeEvent<HTMLInputElement>) => update(key, Number(event.target.value))
  return <><div className="heading"><div><div className="eyebrow">LOJA</div><h1>Configurações</h1><p>Personalize a operação e a experiência da TV.</p></div></div><section className="panel settings-form">{loading ? <div className="empty">Carregando configurações...</div> : <><div className="settings-grid"><label>Nome da loja<input value={form.name} onChange={event => update('name', event.target.value)} /></label><label>Cor de destaque<input type="color" value={form.accentColor} onChange={event => update('accentColor', event.target.value)} /></label><label>Tempo estimado por atendimento<input type="number" value={form.estimatedServiceTime} onChange={number('estimatedServiceTime')} /></label><label>Posições na TV<input type="number" value={form.tvPositions} onChange={number('tvPositions')} /></label><label className="wide-field">Frase da chamada<input value={form.callPhrase} onChange={event => update('callPhrase', event.target.value)} /></label><label>Repetição da chamada<input type="number" value={form.callRepeat} onChange={number('callRepeat')} /></label><label>Volume<input type="range" min="0" max="100" value={form.volume} onChange={number('volume')} /></label></div><div className="checks"><label><input type="checkbox" checked={form.allowVoluntaryExit} onChange={event => update('allowVoluntaryExit', event.target.checked)} /> Permitir saída voluntária</label><label><input type="checkbox" checked={form.allowNewEntries} onChange={event => update('allowNewEntries', event.target.checked)} /> Permitir novas entradas</label></div><button className="primary" onClick={() => void save()} disabled={saving}><Check size={16} /> {saving ? 'Salvando...' : 'Salvar configurações'}</button></>}</section></>
}
